services:
  - type: web
    name: secure-exam-backend
    env: docker
    rootDir: backend
    plan: starter
    envVars:
      - key: APP_CORS_ALLOWED_ORIGINS
        sync: false
      - key: FIREBASE_SERVICE_ACCOUNT_JSON
        sync: false
      - key: KEY_SHARE_WRAP_SECRET
        sync: false
      - key: FIRST_ADMIN_UID
        sync: false

